name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_library:
    runs-on: rust
    steps:
      - uses: actions/checkout@v3

      - name: Rust version
        run: rustc --version && cargo --version

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --verbose

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Format check
        run: cargo fmt --check

      - name: Docs
        run: cargo doc --no-deps

      - name: Security audit
        run: cargo audit