name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-library:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Build and test library crate
    - name: Build library
      run: |
        cd boxy-cli
        cargo build --verbose
    - name: Test library
      run: |
        cd boxy-cli
        cargo test --verbose

  build-binary:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build and test binary crate
    - name: Build binary tests
      run: |
        cd binary-testing
        cargo build --verbose
  
  test-binary:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run binary tests
      run: |
        cd binary-testing
        cargo test --verbose